### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by evan-mcclaugherty** [muchweb/atom-neon-cursor#19]
Love your package! However, when i installed it my macbook pro decided run at 60% cpu power.  I found this out because my laptop got very hot and in the activity monitor it just said "atom helper".  I disabled packages one at a time and found the neon cursor to be the culprit.  I apologize I do not know what information you may need but i'll be happy to give any requested info.

Thanks again,
Evan

**Comment by muchweb** [comment]
Should get better now after #16 is closed
